# Generated by Django 5.0.1 on 2024-02-01 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Варианты название', 'verbose_name_plural': 'Варианты название'},
        ),
        migrations.AlterModelOptions(
            name='optionvalue',
            options={'verbose_name': 'Значение варианты', 'verbose_name_plural': 'Значение варианты'},
        ),
    ]
